language: ruby
rvm:
- 2.7.2
cache: bundler
before_script:
 - chmod +x ./script/cibuild # or do this locally and commit

# Assume bundler is being used, therefore
# the `install` step will run `bundle install` by default.
script: ./script/cibuild

# branch whitelist, only for GitHub Pages
# branches:
  # only:
  # - master

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
  
notifications:
  email: false

sudo: false # route your build to the container-based infrastructure for a faster build

deploy:
  edge: true
  cleanup: false
  provider: pages
  skip_cleanup: true
  keep_history: true
  local_dir: "./_site"  # deploy this directory containing final build
  github_token: $GITHUB_TOKEN # Set in travis-ci.com dashboard
  on:
    branch: master