language: ruby
rvm:
  - 2.6.3
cache: bundler
before_script:
  - chmod +x ./script/cibuild
script: script/cibuild
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
notifications:
  email: false
deploy:
  provider: pages
  edge: true
  cleanup: false
  keep_history: true
  local_dir: "./_site"
  github_token: $GITHUB_TOKEN
  on:
    branch: master
